export enum PostsActionTypes {
  POSTS_LOAD_REQUEST = 'POSTS_REQUEST',
  POSTS_LOAD_SUCCESS = 'POSTS_SUCCESS',
  POSTS_LOAD_FAIL = 'POSTS_FAIL',
  POSTS_LIKES_UPDATE = 'POSTS_LIKES_UPDATE',
  POSTS_DELETE = 'POSTS_DELETE',
  POSTS_RESET = 'POSTS_RESET',

  EXPLORE_POSTS_LOAD_REQUEST = 'EXPLORE_POSTS_REQUEST',
  EXPLORE_POSTS_LOAD_SUCCESS = 'EXPLORE_POSTS_SUCCESS',
  EXPLORE_POSTS_LOAD_FAIL = 'EXPLORE_POSTS_FAIL',
}
